apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: urlshortener
type: Opaque
stringData:
  POSTGRES_DB: urlshortener
  POSTGRES_USER: urlshortener
  POSTGRES_PASSWORD: urlshortener
